---
- hosts: all
  gather_facts: true
  tasks:
    - name: Deploy Network Config
      ansible.builtin.include_role:
        name: network.ospf.deploy
      vars:
        resources:
          - 'ospfv2'
          - 'ospfv3'
          - 'ospf_interfaces'
        data_store:
          scm:
            parent_directory: "/home/rhel"
            origin:
              url: "https://github.com/Ruchip16/validated_content_demo.git"
              token: "{{ token }}"
              user:
                name: Ruchip16
                email: ruchipakhle@gmail.com