---
- hosts: all
  gather_facts: false
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: network.ospf.gather
      vars:
        ansible_network_os: cisco.ios.ios
        resources:
          - 'ospfv2'
          - 'ospfv3'
          - 'ospf_interfaces'