---
- name: Delete VLAN Configuration.
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather configuration.
      cisco.ios.ios_vlans:
        config:
          vlan_id: 1337
        state: deleted